language: android
android:
  components:
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-x86-android-26
  - sys-img-armeabi-v7a-android-17
script:
- "./gradlew build"
notifications:
  slack: argila:bXGzFxqVuwbq5AC2pbP4J2yq
after_success:
- bash scripts/mail.sh
before_install:
- openssl aes-256-cbc -K $encrypted_c64317e97a7a_key -iv $encrypted_c64317e97a7a_iv
  -in gnevo.tar.gz.enc -out gnevo.tar.gz -d
- tar -zxvf gnevo.tar.gz
branches:
  only:
  - 1-travis-support
